export const Majors = [
  `Agricultural business and management`,
  `Agroecology/sustainable agriculture`,
  `Agronomy and crop science`,
  `Animal sciences`,
  `Applied horticulture/horticultural business services`,
  `Equestrian/equine studies`,
  `Food science and technology`,
  `Soil sciences`,
  `Architecture`,
  `Architectural technology/technician`,
  `City/urban, community, and regional planning`,
  `Environmental design`,
  `Landscape architecture`,
  `Area studies`,
  `Ethnic, cultural minority, gender, and group studies`,
  `Biology/biological sciences, general`,
  `Biochemistry`,
  `Biophysics`,
  `Biotechnology`,
  `Botany/plant biology`,
  `Cell/cellular biology and anatomical sciences`,
  `Ecology`,
  `Genetics`,
  `Marine biology and biological oceanography`,
  `Microbiological sciences and immunology`,
  `Molecular biology`,
  `Neuroscience`,
  `Pharmacology and toxicology`,
  `Physiology, pathology, and related sciences`,
  `Radiation biology/radiobiology`,
  `Zoology/animal biology`,
  `Accounting and related services`,
  `Actuarial science`,
  `Administrative assistant and secretarial science`,
  `Business administration, management, and operations`,
  `Business/managerial economics`,
  `Business statistics`,
  `Construction management`,
  `Fashion merchandising`,
  `Finance and financial management services`,
  `General sales, merchandising, and related marketing operations`,
  `Hospitality administration/management`,
  `Hotel, motel, and restaurant management`,
  `Human resources management and services`,
  `Insurance`,
  `International business`,
  `Investments and securities`,
  `Labor and industrial relations`,
  `Management information systems/services`,
  `Marketing/marketing management`,
  `Meeting and event planning`,
  `Project management`,
  `Real estate`,
  `Transportation/mobility management`,
  `Communication and media studies`,
  `Digital communication and media/multimedia`,
  `Journalism`,
  `Photojournalism`,
  `Public relations, advertising, and applied communication`,
  `Radio and television`,
  `Artificial intelligence`,
  `Computer programming`,
  `Computer game programming`,
  `Computer science`,
  `Computer software and media applications`,
  `Computer systems analysis`,
  `Computer systems networking and telecommunications`,
  `Data processing`,
  `Information sciences/studies`,
  `Information technology project management`,
  `Modeling, virtual environments, and simulation`,
  `Carpentry/carpenter`,
  `Adult and continuing education and teaching`,
  `Agricultural teacher education`,
  `Art teacher education`,
  `Bilingual, multilingual, and multicultural education`,
  `Business teacher education`,
  `Early childhood education and teaching`,
  `Early childhood and family studies`,
  `Educational administration and supervision`,
  `Education/teaching of the gifted and talented`,
  `Elementary education and teaching`,
  `English/language arts teacher education`,
  `English as a second language`,
  `Family and consumer sciences/home economics teacher education`,
  `Health teacher education`,
  `Higher education/higher education administration`,
  `Junior high/intermediate/middle school education and teaching`,
  `Kindergarten/preschool education and teaching`,
  `Mathematics teacher education`,
  `Music teacher education`,
  `Physical education teaching and coaching`,
  `Psychology teacher education`,
  `Science teacher education/general science teacher education`,
  `Second language learning`,
  `Secondary education and teaching`,
  `Social science teacher education`,
  `Special education and teaching`,
  `Student counseling and personnel services`,
  `Teaching English as a second or foreign language/ES language instructor`,
  `Technology teacher education/industrial arts teacher education`,
  `Aerospace, ace, aeronautical, and space engineering`,
  `Agricultural engineering`,
  `Architectural engineering`,
  `Biochemical engineering`,
  `Biological/biosystems engineering`,
  `Bioengineering and biomedical engineering`,
  `Chemical engineering`,
  `Civil engineering`,
  `Computer engineering, general`,
  `Construction engineering`,
  `Electrical and electronics engineering`,
  `Engineering chemistry`,
  `Engineering mechanics`,
  `Engineering physics/applied physics`,
  `Engineering science`,
  `Environmental/environmental health engineering`,
  `Geological/geophysical engineering`,
  `Industrial engineering`,
  `Materials engineering`,
  `Mechanical engineering`,
  `Mining and mineral engineering`,
  `Naval architecture and marine engineering`,
  `Nuclear engineering`,
  `Ocean engineering`,
  `Petroleum engineering`,
  `Preengineering`,
  `Surveying engineering`,
  `Polymer/plastics engineering`,
  `Civil engineering technology`,
  `Computer engineering technology`,
  `Drafting/design engineering technologies`,
  `Electrical engineering technologies`,
  `Energy systems technologies`,
  `Environmental control technologies`,
  `Industrial production technologies`,
  `Mechanical engineering/technologies`,
  `Nanotechnology`,
  `Nuclear engineering technology`,
  `Plastics and polymer engineering technology`,
  `Robotics technology`,
  `Telecommunications technology`,
  `American literature (United States and Canada)`,
  `Creative writing`,
  `English literature (British and Commonwealth)`,
  `Rhetoric and composition/writing studies`,
  `Professional, technical, business, and scientific writing`,
  `Apparel and textiles`,
  `Foods, nutrition, and wellness studies`,
  `Housing and human environments`,
  `Human development, family studies, and related services`,
  `African languages, literatures, and linguistics`,
  `Arabic language and literature`,
  `Classics and classical languages, literatures, and linguistics`,
  `Comparative literature`,
  `East Asian languages, literatures, and linguistics`,
  `French language and literature`,
  `German language and literature`,
  `Italian language and literature`,
  `Linguistics`,
  `Russian language and literature`,
  `Spanish language and literature`,
  `Allied health and medical assisting services`,
  `Allied health diagnostic, intervention, and treatment professions`,
  `Alternative and complementary medicine and medical systems`,
  `Athletic training/trainer`,
  `Clinical/medical laboratory science/research and allied professions`,
  `Communication sciences and disorders`,
  `Dental hygiene/hygienist`,
  `Dental laboratory technology/technician`,
  `Dental support services and allied professions`,
  `Dietetics and clinical nutrition services`,
  `Environmental health`,
  `Health and medical administrative services`,
  `Health and wellness`,
  `Health services/allied health/health sciences`,
  `Hospital/health care facilities administration`,
  `Mental and social health services`,
  `Music therapy/therapist`,
  `Nuclear medical technology/technologist`,
  `Nurse anesthetist`,
  `Nursing`,
  `Osteopathic medicine/osteopathy (DO)`,
  `Pharmaceutical marketing and management`,
  `Pharmaceutical sciences`,
  `Physician assistant`,
  `Podiatric medicine/podiatry (DPM)`,
  `Prechiropractic studies`,
  `Predentistry studies`,
  `Premedicine/premedical studies`,
  `Preoccupational therapy studies`,
  `Preoptometry studies`,
  `Prepharmacy studies`,
  `Prephysical therapy studies`,
  `Preveterinary studies`,
  `Public health`,
  `Radiologic technology/science-radiographer`,
  `Rehabilitation and therapeutic professions`,
  `Respiratory care therapy/therapist`,
  `Surgical technology/technologist`,
  `Therapeutic recreation/recreational therapy`,
  `American history (United States)`,
  `European history`,
  `Criminal justice and corrections`,
  `Criminal justice/law enforcement administration`,
  `Cyber/computer forensics/counterterrorism`,
  `Financial forensics and fraud investigation`,
  `Fire protection`,
  `Forensic science and technology`,
  `Homeland security`,
  `Legal assistant/paralegal`,
  `Prelaw studies`,
  `General studies`,
  `Humanities/humanistic studies`,
  `Liberal arts and sciences/liberal studies`,
  `Library and archives assisting`,
  `Applied mathematics`,
  `Financial mathematics`,
  `Mathematics`,
  `Statistics`,
  `Airframe mechanics and aircraft maintenance technology`,
  `Automobile/automotive mechanics technology`,
  `Electrical/electronics maintenance and repair technology`,
  `Heating, air conditioning, ventilation, and refrigeration maintenance technology`,
  `(General code only)`,
  `Biological and physical sciences`,
  `Business analytics`,
  `Data science`,
  `Human biology`,
  `International/global studies`,
  `Marine sciences`,
  `Mathematics and computer science`,
  `Nutrition sciences`,
  `Sustainability studies`,
  `Environmental science`,
  `Environmental studies`,
  `Fishing and fisheries sciences and management`,
  `Forestry`,
  `Natural resources management and policy`,
  `Wildlife, fish, wildlands science/management`,
  `Health and physical education/fitness`,
  `Outdoor education`,
  `Parks and recreation facilities management`,
  `Sport and fitness administration/management`,
  `Sports studies`,
  `Cosmetology and personal grooming services`,
  `Culinary arts and related services`,
  `Philosophy`,
  `Religion/religious studies`,
  `Analytical chemistry`,
  `Astronomy`,
  `Astrophysics`,
  `Atmospheric sciences and meteorology`,
  `Atomic/molecular physics`,
  `Chemistry`,
  `Forensic chemistry`,
  `Geological and Earth sciences/geosciences`,
  `Materials science`,
  `Nuclear physics`,
  `Oceanography, chemical and physical`,
  `Organic chemistry`,
  `Paleontology`,
  `Physical chemistry`,
  `Physics`,
  `Planetary astronomy and science`,
  `Clinical psychology`,
  `Developmental and child psychology`,
  `Experimental psychology`,
  `Industrial and organizational psychology`,
  `Social psychology`,
  `Human services, general`,
  `Public administration`,
  `Public policy analysis`,
  `Social work`,
  `Anthropology`,
  `Archaeology`,
  `Criminology`,
  `Economics`,
  `Geography`,
  `International relations and affairs`,
  `Political science and government`,
  `Sociology`,
  `Religious education`,
  `Religious music and worship`,
  `Theological and ministerial studies`,
  `Art history, criticism, and conservation`,
  `Arts, entertainment, and media management`,
  `Dance`,
  `Digital arts`,
  `Drama and theater arts`,
  `Design and applied arts`,
  `Fashion/apparel design`,
  `Film/video and photographic arts`,
  `Fine and studio art`,
  `Game and interactive media design`,
  `Graphic design`,
  `Interior design`,
  `Music`,
  `Music history, literature, and theory`,
  `Music performance, general`,
  `Music technology`,
  `Music theory and composition`,
  `Musical theater`,
  `Photography`,
  `Technical theater/theater design and technology`,
  `Voice and opera`,
  `Undecided`,
  `Other (not listed)`,
] as const;

export type Major = (typeof Majors)[number];
