CREATE TABLE `hacker_profile` (
	`applicationId` text PRIMARY KEY NOT NULL,
	`phoneNumber` text DEFAULT '' NOT NULL,
	`dateOfBirth` text DEFAULT '' NOT NULL,
	`shirtSize` text DEFAULT '' NOT NULL,
	`gender` text DEFAULT '' NOT NULL,
	`ethnicity` text DEFAULT '' NOT NULL,
	`levelOfStudy` text DEFAULT '' NOT NULL,
	`gradYear` text DEFAULT '' NOT NULL,
	`major` text DEFAULT '' NOT NULL,
	`skillLevel` text DEFAULT '' NOT NULL,
	`hackathonsAttended` text DEFAULT '' NOT NULL,
	`addressLine1` text DEFAULT '' NOT NULL,
	`addressLine2` text DEFAULT '' NOT NULL,
	`city` text DEFAULT '' NOT NULL,
	`state` text DEFAULT '' NOT NULL,
	`zipCode` text DEFAULT '' NOT NULL,
	`country` text DEFAULT '' NOT NULL,
	`dietaryAdditionalDetails` text DEFAULT '' NOT NULL,
	`dietaryVegetarian` integer DEFAULT false NOT NULL,
	`dietaryVegan` integer DEFAULT false NOT NULL,
	`dietaryGlutenFree` integer DEFAULT false NOT NULL,
	`dietaryDairyFree` integer DEFAULT false NOT NULL,
	`dietaryNutAllergy` integer DEFAULT false NOT NULL,
	`dietaryShellfishAllergy` integer DEFAULT false NOT NULL,
	`dietaryKosher` integer DEFAULT false NOT NULL,
	`dietaryHalal` integer DEFAULT false NOT NULL,
	`dietaryPescatarian` integer DEFAULT false NOT NULL,
	`dietaryOther` integer DEFAULT false NOT NULL,
	`mlhCodeOfConduct` integer DEFAULT false NOT NULL,
	`mlhPrivacyPolicy` integer DEFAULT false NOT NULL,
	`mlhMailingList` integer DEFAULT false NOT NULL,
	FOREIGN KEY (`applicationId`) REFERENCES `hacker_answer`(`applicationId`) ON UPDATE no action ON DELETE no action
);
